remove old options from the rcsoccersim script

diff --git a/src/rcsoccersim.in b/src/rcsoccersim.in
--- a/src/rcsoccersim.in
+++ b/src/rcsoccersim.in
@@ -35,19 +35,13 @@ if test $# -eq 0; then
     else
         MON=`which rcssmonitor 2> /dev/null`
         if test $? -eq 1; then
-            MON=`which rcssmonitor_frameview 2> /dev/null`
-            if test $? -eq 1; then
-              MON=`which rcssmonitor_classic 2> /dev/null`
-              if test $? -eq 1; then
-                echo "Error: No monitors can be found in your PATH and the"
-                echo "       RCSSMONITOR environment variable is not set. Please"
-                echo "       add rcssmonitor or rcssmonitor_classic to you PATH,"
-                echo "       or set the RCSSMONITOR environment variable to the"
-                echo "       executable you wish to use."
-                echo ""
-                exit 1
-              fi
-            fi
+            echo "Error: No monitors can be found in your PATH and the"
+            echo "       RCSSMONITOR environment variable is not set. Please"
+            echo "       add rcssmonitor or rcssmonitor_classic to you PATH,"
+            echo "       or set the RCSSMONITOR environment variable to the"
+            echo "       executable you wish to use."
+            echo ""
+            exit 1
         fi
     fi
 else
@@ -58,24 +52,6 @@ else
             MON=`which rcssmonitor 2> /dev/null`
             if test $? -eq 1; then
                 echo "Error: rcssmonitor cannot be found in your PATH"
-                echo ""
-                exit 1
-            fi
-            ;;
-
-            -frameview)
-            MON=`which rcssmonitor_frameview 2> /dev/null`
-            if test $? -eq 1; then
-                echo "Error: rcssmonitor_frameview cannot be found in your PATH"
-                echo ""
-                exit 1
-            fi
-            ;;
-
-            -classic)
-            MON=`which rcssmonitor_classic 2> /dev/null`
-            if test $? -eq 1; then
-                echo "Error: rcssmonitor_classic cannot be found in your PATH"
                 echo ""
                 exit 1
             fi
